public class Calendarr {
Integer i;
    public String getG() {
        return null;
    }


    public String getF() {
        return null;
    }


    public String getE() {
        return null;
    }


    public String getD() {
        return null;
    }


    public String getC() {
        return null;
    }


    public void getA() {
        for(i=1;i<=7;i++)
        {
        System.debug(i);
        }
        
    }

//Date dateObj;
//Integer dy=dateObj.day();
//Integer mnth=dateObj.month();
//Integer year=dateObj.year();
//List<integer>ls1=new List<Integer>();


Integer a,count;

public Integer b{get;set;}
    public List<Integer> datee{get;set;}
    public List<Integer> getWeekdays() {
      datee=new List<Integer>();
      for(a=1;a<=7;a++)
      {
      
      datee.add(a); 
      }
      
  //for(b=1;b<=30;b++){
  //System.debug(b);
   //}
     return datee;
            
     }

}